FROM golang:1.11.1-alpine

# Copy the local package files to the container's workspace.
COPY cmds . /go/bin/

# execute 
ENTRYPOINT ["/go/bin/cmds/server.bin"]
# Document that the service listens on port 8080.
EXPOSE 9090
