FROM golang:1.11.1-alpine

CMD cd $GOPATH
ADD . /go/src/github.com/alexkylt/message_broker

RUN apk update && apk upgrade && \
    apk add --no-cache git gcc

RUN go get -d -v ./...

RUN go get -u golang.org/x/lint/golint

RUN go get golang.org/x/tools/cmd/goimports

WORKDIR /go/src/github.com/alexkylt/message_broker
# ENV GOOS=linux
# ENV GOARCH=amd64

ENTRYPOINT ["go"]
